import { NextRequest, NextResponse } from 'next/server';

export const dynamic = 'force-dynamic';

interface ConversationMessage {
  id: string;
  type: 'user' | 'bot';
  content: string;
  timestamp: Date;
}

interface UserContext {
  pregnancyWeek: number;
  riskFactors: string[];
  previousSymptoms: string[];
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { message, conversationHistory, userContext } = body as {
      message: string;
      conversationHistory: ConversationMessage[];
      userContext: UserContext;
    };

    if (!message) {
      return NextResponse.json(
        { error: 'No message provided' },
        { status: 400 }
      );
    }

    // Voicechat2 AI Conversation API integration
    const voicechat2ApiKey = process.env.VOICECHAT2_API_KEY;
    
    if (!voicechat2ApiKey) {
      // Fallback to mock AI response for development
      return NextResponse.json({
        text: generateMockResponse(message, userContext),
        audioUrl: null, // Would be generated by Voicechat2 TTS
        assessment: generateMockAssessment(message)
      });
    }

    // Prepare conversation context for Voicechat2
    const conversationContext = {
      currentMessage: message,
      history: conversationHistory.map(msg => ({
        role: msg.type === 'user' ? 'user' : 'assistant',
        content: msg.content
      })),
      userProfile: {
        pregnancyWeek: userContext.pregnancyWeek,
        riskFactors: userContext.riskFactors,
        previousSymptoms: userContext.previousSymptoms
      },
      systemPrompt: `You are SafeMama AI, a compassionate maternal health assistant. You help pregnant women with:
- Symptom assessment and monitoring
- Pregnancy-related questions and concerns
- Risk evaluation and recommendations
- Emotional support and reassurance
- Connecting them with appropriate healthcare resources

Always be empathetic, professional, and prioritize safety. If symptoms seem serious, recommend immediate medical attention.`
    };

    // Call Voicechat2 AI Conversation API
    const response = await fetch('https://api.voicechat2.com/v1/chat', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${voicechat2ApiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(conversationContext),
    });

    if (!response.ok) {
      throw new Error(`Voicechat2 API error: ${response.statusText}`);
    }

    const result = await response.json();

    // Generate audio response using Voicechat2 TTS
    const audioResponse = await fetch('https://api.voicechat2.com/v1/tts', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${voicechat2ApiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        text: result.response,
        voice: 'female_caring', // Maternal health appropriate voice
        speed: 1.0,
        pitch: 1.0
      }),
    });

    let audioUrl = null;
    if (audioResponse.ok) {
      const audioResult = await audioResponse.json();
      audioUrl = audioResult.audioUrl;
    }

    return NextResponse.json({
      text: result.response,
      audioUrl: audioUrl,
      assessment: generateAssessmentFromResponse(result.response, message)
    });

  } catch (error) {
    console.error('AI chat error:', error);
    
    // Fallback response
    return NextResponse.json({
      text: "I understand you're experiencing some symptoms. Let me help you assess this. Can you tell me more about the severity and duration of your symptoms?",
      audioUrl: null,
      assessment: {
        tier: 1,
        advice: "Continue monitoring and provide more details",
        reasons: ["Insufficient information for assessment"]
      }
    });
  }
}

function generateMockResponse(message: string, userContext: UserContext): string {
  const lowerMessage = message.toLowerCase();
  
  if (lowerMessage.includes('cramping') || lowerMessage.includes('cramp')) {
    return "I understand you're experiencing cramping. This can be normal during pregnancy as your uterus grows, but it's important to monitor the characteristics. Can you tell me more about the intensity, location, and whether it's accompanied by any other symptoms like bleeding or severe pain?";
  }
  
  if (lowerMessage.includes('tired') || lowerMessage.includes('fatigue')) {
    return "Fatigue is very common during pregnancy, especially in the first and third trimesters. At 24 weeks, your body is working hard to support your growing baby. Are you getting enough rest and staying hydrated? Let's also discuss your sleep patterns and any other symptoms you might be experiencing.";
  }
  
  if (lowerMessage.includes('pain') || lowerMessage.includes('hurt')) {
    return "I'm concerned about the pain you're describing. Pain during pregnancy can have various causes, some normal and some requiring attention. Can you describe the type of pain, its location, intensity on a scale of 1-10, and what makes it better or worse?";
  }
  
  if (lowerMessage.includes('bleeding') || lowerMessage.includes('blood')) {
    return "Any bleeding during pregnancy should be evaluated by a healthcare provider. While some light spotting can be normal, it's important to rule out any serious conditions. Please contact your healthcare provider immediately or go to the nearest emergency room if the bleeding is heavy or accompanied by severe pain.";
  }
  
  // Default empathetic response
  return "Thank you for sharing your concerns with me. I'm here to help you navigate your pregnancy journey safely. Can you provide more details about what you're experiencing so I can better assist you?";
}

function generateMockAssessment(message: string) {
  const lowerMessage = message.toLowerCase();
  
  if (lowerMessage.includes('severe') || lowerMessage.includes('intense') || lowerMessage.includes('unbearable')) {
    return {
      tier: 3,
      advice: "Seek immediate medical attention",
      reasons: ["Severe symptoms described"]
    };
  }
  
  if (lowerMessage.includes('bleeding') || lowerMessage.includes('blood')) {
    return {
      tier: 3,
      advice: "Contact healthcare provider immediately",
      reasons: ["Bleeding during pregnancy"]
    };
  }
  
  if (lowerMessage.includes('pain') && (lowerMessage.includes('severe') || lowerMessage.includes('sharp'))) {
    return {
      tier: 2,
      advice: "Schedule appointment within 24 hours",
      reasons: ["Concerning pain symptoms"]
    };
  }
  
  return {
    tier: 1,
    advice: "Continue monitoring and provide more details",
    reasons: ["Mild symptoms, needs more information"]
  };
}

function generateAssessmentFromResponse(aiResponse: string, userMessage: string) {
  // Analyze AI response to determine risk assessment
  const lowerResponse = aiResponse.toLowerCase();
  const lowerMessage = userMessage.toLowerCase();
  
  if (lowerResponse.includes('immediate') || lowerResponse.includes('emergency') || lowerResponse.includes('urgent')) {
    return {
      tier: 3,
      advice: "Seek immediate medical attention",
      reasons: ["AI identified urgent symptoms"]
    };
  }
  
  if (lowerResponse.includes('contact your healthcare provider') || lowerResponse.includes('schedule an appointment')) {
    return {
      tier: 2,
      advice: "Contact healthcare provider soon",
      reasons: ["AI recommends professional evaluation"]
    };
  }
  
  return {
    tier: 1,
    advice: "Continue monitoring",
    reasons: ["AI suggests ongoing observation"]
  };
}


