[build]
  command = "npm run build"
  publish = ".next"

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"

# API routes
[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache API responses for a short time
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "public, max-age=60"

