type Tier = 1|2|3;

export function RiskBanner({ tier, reason }: { tier: Tier; reason?: string }) {
  const cfg = {
    1: { wrap: "bg-[rgb(var(--success))]/60 text-slate-800 border border-[rgb(var(--success))]", title: "Low risk — monitor" },
    2: { wrap: "bg-[rgb(var(--warning))]/60 text-slate-900 border border-[rgb(var(--warning))]", title: "Visit a clinic within 24 hours" },
    3: { wrap: "bg-[rgb(var(--destructive))]/60 text-[rgb(var(--destructive-foreground))] border-2 border-[rgb(var(--destructive))]", title: "Emergency — go now" },
  }[tier];

  return (
    <section className={`rounded-xl p-4 ${cfg.wrap}`}>
      <p className="font-playfair text-lg">{cfg.title}</p>
      {reason && <p className="mt-1 text-sm opacity-85">Reason: {reason}</p>}
      <p className="mt-2 text-xs opacity-70">Advice generated by rules v1.0 — not a diagnosis.</p>
    </section>
  );
}
export default RiskBanner;