export function clinicianEmail({ patient, summary, triage, when, location }:{
  patient: { id:string; name?:string; phone?:string; weeks?:number };
  summary: { chiefConcern:string; keyPoints:string[]; transcript?:string };
  triage: { tier: 1|2|3; reasons:string[]; action:string };
  when: string;
  location?: string;
}) {
  return `
Subject: Patient check-in — Tier ${triage.tier}

Patient: ${patient.name || "Unknown"} (ID ${patient.id})
Weeks: ${patient.weeks ?? "n/a"}   Phone: ${patient.phone ?? "n/a"}
Time: ${when}   ${location ? `Location: ${location}` : ""}

Chief concern: ${summary.chiefConcern}

Key points:
- ${summary.keyPoints.join("\n- ") || "No specific keywords extracted."}

Assessment (rules-based, not a diagnosis):
- Tier ${triage.tier}: ${triage.action}
Reasons:
- ${triage.reasons.join("\n- ") || "n/a"}

Full transcript:
${summary.transcript ?? "omitted"}

— This message was generated by the SafeMama assistant. Not a diagnosis.`;
}
