/* emails/ClinicianSummaryEmail.tsx */
import * as React from "react";
import {
  Body,
  Button,
  Column,
  Container,
  Head,
  Hr,
  Html,
  Img,
  Link,
  Preview,
  Row,
  Section,
  Text,
} from "@react-email/components";

type Urgency = "urgent" | "soon" | "routine";

export type ClinicianSummaryProps = {
  patientName: string;
  reportDateISO: string;              // e.g., new Date().toISOString()
  trimester?: string;                 // "1", "2", "3" or "Unknown"
  symptoms: string[];                 // ["Severe headache", "Blurred vision"]
  aiSummary: string;                  // clean paragraph
  recommendedAction?: string;         // short directive ("Urgent medical attention is advised.")
  sessionId?: string;                 // optional cross-ref
  appUrl?: string;                    // https://safemama.netlify.app
  clinicianReplyHint?: string;        // e.g., "Reply to this email to reach the patient via SafeMama"
  urgency?: Urgency;
  logoUrl?: string;                   // optional SafeMama logo (absolute URL)
};

const pastel = {
  ink: "#1B2735",
  slate600: "#475569",
  slate300: "#CBD5E1",
  white: "#ffffff",
  blush: "#FFF7FA",
  mint: "#EAF7F6",
  gold: "#D4AF37",
  redSoft: "#FEE2E2",
  redText: "#7F1D1D",
};

const urgencyStyles: Record<Urgency, { bg: string; text: string; label: string }> = {
  urgent: { bg: pastel.redSoft, text: pastel.redText, label: "Urgent" },
  soon:   { bg: "#FEF3C7", text: "#7C2D12", label: "Soon" },
  routine:{ bg: "#ECFDF5", text: "#064E3B", label: "Routine" },
};

export default function ClinicianSummaryEmail({
  patientName,
  reportDateISO,
  trimester = "Unknown",
  symptoms,
  aiSummary,
  recommendedAction = "",
  sessionId,
  appUrl = "https://safemama.netlify.app",
  clinicianReplyHint,
  urgency = "urgent",
  logoUrl,
}: ClinicianSummaryProps) {
  const reportDate = new Date(reportDateISO);
  const dateStr = reportDate.toLocaleString(undefined, {
    year: "numeric", month: "short", day: "2-digit",
    hour: "2-digit", minute: "2-digit",
  });

  const u = urgencyStyles[urgency];

  return (
    <Html>
      <Head />
      <Preview>{`SafeMama: ${urgency === "urgent" ? "URGENT " : ""}Summary for ${patientName}`}</Preview>
      <Body style={styles.body}>
        <Container style={styles.container}>
          {/* Header */}
          <Section style={{ marginTop: 8, marginBottom: 16 }}>
            <Row style={{ alignItems: "center" }}>
              <Column style={{ width: "48px" }}>
                {logoUrl ? (
                  <Img src={logoUrl} width="40" height="40" alt="SafeMama" style={{ borderRadius: 8 }} />
                ) : (
                  <div style={{ width: 40, height: 40, borderRadius: 8, background: pastel.gold }} />
                )}
              </Column>
              <Column>
                <Text style={styles.h1}>SafeMama Symptom Report</Text>
                <Text style={styles.muted}>Generated by the SafeMama Antenatal Companion</Text>
              </Column>
            </Row>
          </Section>

          {/* Patient + Meta */}
          <Section style={styles.card}>
            <Row>
              <Column>
                <Text style={styles.label}>Patient</Text>
                <Text style={styles.value}>{patientName || "Unknown"}</Text>
              </Column>
              <Column>
                <Text style={styles.label}>Date</Text>
                <Text style={styles.value}>{dateStr}</Text>
              </Column>
              <Column>
                <Text style={styles.label}>Trimester</Text>
                <Text style={styles.value}>{trimester}</Text>
              </Column>
            </Row>

            {sessionId ? (
              <>
                <Hr style={styles.hr} />
                <Text style={styles.smallMuted}>Session ID: {sessionId}</Text>
              </>
            ) : null}
          </Section>

          {/* Urgency Banner */}
          <Section style={{ ...styles.banner, background: u.bg, color: u.text }}>
            <Text style={{ margin: 0, fontWeight: 700 }}>
              {u.label} — {recommendedAction || "Please review at your earliest convenience."}
            </Text>
          </Section>

          {/* Symptoms */}
          <Section style={styles.card}>
            <Text style={styles.h2}>Reported Symptoms</Text>
            <ul style={styles.ul}>
              {symptoms?.length ? symptoms.map((s, i) => <li key={i} style={styles.li}>{s}</li>) : <li style={styles.li}>Not specified</li>}
            </ul>
          </Section>

          {/* Summary */}
          <Section style={styles.card}>
            <Text style={styles.h2}>AI Summary</Text>
            <Text style={styles.p}>{aiSummary}</Text>
          </Section>

          {/* CTA */}
          <Section style={{ textAlign: "center", marginTop: 8 }}>
            <Button
              style={styles.primaryBtn}
              href={`${appUrl}/doctor/reports${sessionId ? `?q=${encodeURIComponent(sessionId)}` : ""}`}
            >
              Open in SafeMama
            </Button>
          </Section>

          {/* Footer */}
          <Hr style={styles.hr} />
          <Text style={styles.smallMuted}>
            {clinicianReplyHint || "This message was sent via SafeMama on behalf of the patient."}
          </Text>
          <Text style={styles.tiny}>
            © {new Date().getFullYear()} SafeMama. This email may contain sensitive health information intended for the recipient.
          </Text>

          {/* Link fallback */}
          <Text style={styles.tiny}>
            Trouble with the button? Visit:{" "}
            <Link href={`${appUrl}/doctor/reports`} style={{ color: pastel.slate600 }}>
              {appUrl}/doctor/reports
            </Link>
          </Text>
        </Container>
      </Body>
    </Html>
  );
}

const styles: Record<string, React.CSSProperties> = {
  body: {
    background: pastel.blush,
    margin: 0,
    padding: "24px 0",
    fontFamily: '"Inter", system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif',
    color: pastel.ink,
  },
  container: {
    width: "100%",
    maxWidth: 640,
    margin: "0 auto",
    background: pastel.white,
    borderRadius: 16,
    padding: 24,
    border: `1px solid ${pastel.slate300}`,
  },
  h1: { margin: 0, fontSize: 18, fontWeight: 800, color: pastel.ink },
  h2: { margin: "0 0 8px", fontSize: 16, fontWeight: 700, color: pastel.ink },
  p: { margin: 0, lineHeight: 1.6, color: pastel.ink },
  label: { margin: 0, fontSize: 12, color: pastel.slate600, textTransform: "uppercase", letterSpacing: 0.5 },
  value: { margin: "4px 0 0", fontSize: 14, fontWeight: 600, color: pastel.ink },
  hr: { borderColor: pastel.slate300, margin: "16px 0" },
  card: {
    background: pastel.white,
    border: `1px solid ${pastel.slate300}`,
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
  },
  banner: {
    borderRadius: 12,
    padding: "12px 16px",
    margin: "8px 0 12px",
    border: `1px solid ${pastel.slate300}`,
  },
  primaryBtn: {
    backgroundColor: pastel.gold,
    color: "#4A3A00",
    padding: "12px 18px",
    borderRadius: 10,
    fontWeight: 700,
    textDecoration: "none",
    display: "inline-block",
  },
  muted: { color: pastel.slate600 },
  smallMuted: { fontSize: 12, color: pastel.slate600 },
  tiny: { fontSize: 11, color: pastel.slate600, marginTop: 6 },
  ul: { margin: 0, paddingLeft: 18 },
  li: { marginBottom: 6, lineHeight: 1.4 },
};
